apiVersion: v1
kind: Namespace
metadata:
  name: qa
  labels:
    name: qa
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: res-quota
  namespace: qa
spec:
  hard:
    pods: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: qa
  name: dp-quota
  labels:
    app: front
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pod-quota
  template:
    metadata:
      labels:
        app: pod-quota
    spec:
      containers:
      - name: nginx
        image: nginx:alpine