apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-test2
  labels:
    app: front2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-label2
  template:
    metadata:
      labels:
        app: pod-label2
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
---
apiVersion: v1
kind: Service
metadata:
  name: svc-test2
  labels:
    app: front2
spec:
  type: NodePort
  selector:
    app: pod-label2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80