apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-test
  labels:
    app: front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-label
  template:
    metadata:
      labels:
        app: pod-label
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
---
apiVersion: v1
kind: Service
metadata:
  name: src-test
  labels:
    app: front
spec:
  selector:
    app: pod-label
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80