apiVersion: v1
kind: Pod
metadata:
  name: limit-ram
spec:
  containers:
    - name: memory-demo
      image: polinux/stress
      resources:
        requests:
          memory: "100Mi"
        limits:
          memory: "200Gi"
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
